name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to ACR using username and password
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/chatapp:latest

      # Step 4: Push the Docker image to ACR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/chatapp:latest
