name: Deploy Docker Image to Container App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure using Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azure@v1
        with:
          azure-cli-version: 'latest'

      - name: Log in to Azure
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Step 3: Log in to ACR
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      # Step 4: Pull the Docker image from ACR
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/chatapp:latest

      # Step 5: Deploy the Docker image to the container app
      - name: Deploy to Azure Container App
        run: |
          az containerapp update --name your-container-app-name --resource-group your-resource-group-name --image ${{ secrets.ACR_NAME }}.azurecr.io/chatapp:latest

      # Optional: Step 6: Confirm deployment
      - name: Confirmation
        run: echo "Docker image successfully deployed to Azure Container App."
